Remove strange hack in http client
nerves-project/nerves pull request #587
Opened 2021-01-19 19:34 UTC by ConnorRigby

I tested this on all of our latest systems from the last few versions. I'm not sure what this was trying to accomplish, but i don't think it's necessary anymore and I can't sleep at night knowing it exists.

2021-01-19 20:08 UTC, fhunleth approved these changes

2021-01-19 21:42 UTC, mobileoverlord commented
The `+` symbol is part of the resetved set that according to the spec should be percent encoded. https://tools.ietf.org/html/rfc3986

I've tested this in iex and URI.encode alone does not encode them. The `+` specifically has special meaning to which it will be interpreted as a space. If anything the code should possibly be updated to handle more of the reserved characterset.

2021-01-19 21:47 UTC, fhunleth commented
@mobileoverlord The spec you referenced has quite a few reserved characters. Isn't it odd to single out `+` for handling and not any of the other ones?

2021-01-19 21:48 UTC, mobileoverlord commented
I think this was an accidental addition for an isolated case that wasn't tied back until now. As I mentioned, if anything we should probably encode the others in the reserved set instead of removing just this one.

2021-01-19 21:51 UTC, fhunleth commented
@ConnorRigby Do you want to rework the PR to include the other characters?

Just as a side comment, is something broken when it comes to URI encoding? Like why do we have to deal with this. It seems like this should apply to everyone?

2021-01-19 21:52 UTC, fhunleth requested changes
Changed approval based on comments.

2021-01-28 19:31 UTC, fhunleth commented
Closing out of lack of interest in cleaning it up.

2021-01-28 19:31 UTC, closed without merging