Add mix task to load nerves_defconfig
nerves-project/nerves pull request #929
Opened 2023-11-11 23:14 UTC by amclain

This PR adds the command `mix nerves.loaddefconfig` to copy changes made to `nerves_defconfig` over to the Nerves artifact. It does the opposite of running `make savedefconfig` from the artifact.

2023-11-12 13:01 UTC, jjcarstens requested changes

2023-11-12 13:01 UTC, jjcarstens commented on lib/mix/tasks/nerves.loaddefconfig.ex
> +  This is the opposite of `make savedefconfig`.
```suggestion
  @shortdoc "Load nerves_defconfig into the Nerves artifact"

  @moduledoc """
  Load the nerves_defconfig configuration into the Nerves artifact.
  This is the opposite of `make savedefconfig`.
```

I don't think this is quite right. This is only used during build and development but the phrasing of this doc makes it sound like I can load into an already compiled artifact which is not correct.

Maybe mirroring as `nerves.create_build` would be better? Or just changing doc to reflect this loads configuration to prepare for artifact build?

2023-11-12 14:34 UTC, fhunleth commented
I feel this is an advanced feature since you have to know what you're doing since not all Buildroot configuration updates will actually rebuild what you've changed. In fact, I field questions on it with some regularity, so making a helper to encourage this workflow feels like it will create more support requests. The better answer is to erase and start over.

Since we talk about removing in tree Buildroot development on an annual basis, perhaps this is a better addition to `nerves_systems`. And then add an explicit warning that this is a best effort feature and if it doesn't work, then do a full rebuild.

2023-11-21 04:31 UTC, amclain commented
Sure, having `nerves_systems` do this instead makes sense. I'll move it over there and update it to work with the out of tree builds.

2023-11-21 04:31 UTC, closed without merging